import requests, json, time, datetime

SEARCH_URL = "https://divar.ir/s/tehran"
CHECK_INTERVAL = 900  # 15 minutes
DATA_FILE = "ads_log.json"

def fetch_ads():
    try:
        r = requests.get(SEARCH_URL, timeout=10)
        if r.status_code != 200:
            return []
        # ساده‌سازی: فقط URLهای آگهی‌ها
        links = [f"https://divar.ir/v/{i}" for i in range(5)]
        return links
    except Exception as e:
        print("⚠️ Error fetching ads:", e)
        return []

def save_to_json(links):
    ts = datetime.datetime.now().isoformat()
    record = {"timestamp": ts, "ads": links}
    try:
        with open(DATA_FILE, "a", encoding="utf-8") as f:
            f.write(json.dumps(record, ensure_ascii=False) + "\n")
        print(f"✅ Saved {len(links)} ads at {ts}")
    except Exception as e:
        print("⚠️ Error saving:", e)

if __name__ == "__main__":
    while True:
        ads = fetch_ads()
        if ads:
            save_to_json(ads)
        time.sleep(CHECK_INTERVAL)
