name: Hamahang Divar Sender

on:
  workflow_run:
    workflows: ["Hamahang Auto Notify"]
    types:
      - completed

jobs:
  send:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests jdatetime

      - name: Run Divar Sender
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        run: |
          python divar_sender.py
