name: Hamahang OAuth Receiver (Auto)

on:
  workflow_dispatch:
    inputs:
      code:
        description: "Authorization code from Divar OAuth callback"
        required: true
      client_id:
        description: "Divar app slug (client_id)"
        required: true
        default: "bloom-pine-jester"
      redirect_uri:
        description: "Redirect URI registered in Divar"
        required: true
        default: "https://alirezalu1404.github.io/hamahang-callback/index.html"

jobs:
  exchange_token:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip requests

      - name: Exchange OAuth Code for Access Token
        env:
          CLIENT_SECRET: ${{ secrets.DIVAR_CLIENT_SECRET }}
        run: |
          import requests, json, os
          token_url = "https://api.divar.ir/oauth/token"
          payload = {
              "client_id": "${{ github.event.inputs.client_id }}",
              "client_secret": os.getenv("CLIENT_SECRET"),
              "code": "${{ github.event.inputs.code }}",
              "grant_type": "authorization_code",
              "redirect_uri": "${{ github.event.inputs.redirect_uri }}"
          }
          headers = {"Content-Type": "application/json"}
          r = requests.post(token_url, json=payload, headers=headers)
          os.makedirs("data", exist_ok=True)
          with open("data/divar_token.json", "w", encoding="utf-8") as f:
              f.write(json.dumps(r.json(), indent=2, ensure_ascii=False))
          print("✅ Token saved to data/divar_token.json")
          print("Response:", r.text)

      - name: Upload Token Artifact
        uses: actions/upload-artifact@v4
        with:
          name: divar-token
          path: data/divar_token.json
