name: 🔐 Hamahang OAuth Fetch (Auto)

on:
  workflow_dispatch:
    inputs:
      AUTH_CODE:
        description: 'Authorization code from Divar OAuth callback'
        required: true

jobs:
  get-token:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: pip install requests

    - name: Fetch OAuth Token from Divar
      env:
        CLIENT_ID: ${{ secrets.CLIENT_ID }}
        CLIENT_SECRET: ${{ secrets.DIVAR_CLIENT_SECRET }}
        REDIRECT_URI: ${{ secrets.REDIRECT_URI }}
        AUTH_CODE: ${{ github.event.inputs.AUTH_CODE }}
      run: |
        import requests, json, os
        url = "https://api.divar.ir/oauth/token"
        payload = {
            "client_id": os.getenv("CLIENT_ID"),
            "client_secret": os.getenv("CLIENT_SECRET"),
            "code": os.getenv("AUTH_CODE"),
            "grant_type": "authorization_code",
            "redirect_uri": os.getenv("REDIRECT_URI")
        }
        headers = {"Content-Type": "application/json"}
        r = requests.post(url, json=payload, headers=headers)
        print("🔍 Status:", r.status_code)
        print("📥 Response:", r.text)
        if r.status_code == 200:
            token_data = r.json()
            with open("data/divar_token.json", "w") as f:
                json.dump(token_data, f, indent=2)
            print("✅ Token saved successfully to data/divar_token.json")
        else:
            print("❌ Error:", r.text)
      shell: python
