name: Hamahang Proxy Receiver

on:
  workflow_dispatch:  # فعلاً دستی اجرا می‌شود تا تست شود

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flask requests

      - name: Run Proxy Receiver
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        run: |
          python proxy_receiver.py
